[project]
name = "pccr-estimator"
version = "0.0.1"
requires-python = "==3.11.4"
dependencies = [
  "shiny>=0.7.0",
  "numpy>=1.23",
  "pandas>=1.5",
  "scipy>=1.9",
  "joblib>=1.2",
  "scikit-learn>=1.2",
  "tabpfn>=0.1.10",
]